/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estructurasdatos;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author win7
 */
public class GUI_Lista extends javax.swing.JFrame {
    DefaultListModel<String> model_lista;
    CLista lista = new CLista(); 
     
    /**
     * Creates new form GUI_Lista
     */
    public GUI_Lista() {
        initComponents();
        
        this.setTitle("Lista Enlazada");
        this.setResizable(false);
        
        model_lista = new DefaultListModel<>();
        this.jList_lista.setModel(model_lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_lista = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField_elemento = new javax.swing.JTextField();
        jButton_agregar = new javax.swing.JButton();
        jButton_eliminar_elemento = new javax.swing.JButton();
        jButton_buscar = new javax.swing.JButton();
        jLabel_tamanio = new javax.swing.JLabel();
        jSpinner_posicion = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jButton_insertar = new javax.swing.JButton();
        jButton_eliminar_posicion = new javax.swing.JButton();
        jButton_busca_posicion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel1.setText("Listas");

        jList_lista.setEnabled(false);
        jScrollPane1.setViewportView(jList_lista);

        jLabel2.setText("Elemento:");

        jButton_agregar.setText("Agregar");
        jButton_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_agregarMouseClicked(evt);
            }
        });

        jButton_eliminar_elemento.setText("Eliminar  Elemento");
        jButton_eliminar_elemento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_eliminar_elementoMouseClicked(evt);
            }
        });

        jButton_buscar.setText("Buscar Elemento");
        jButton_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_buscarMouseClicked(evt);
            }
        });

        jLabel_tamanio.setText("Tamaño: 0");

        jLabel3.setText("Posición:");

        jButton_insertar.setText("Insertar");
        jButton_insertar.setMaximumSize(new java.awt.Dimension(62, 33));
        jButton_insertar.setMinimumSize(new java.awt.Dimension(62, 33));
        jButton_insertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_insertarMouseClicked(evt);
            }
        });

        jButton_eliminar_posicion.setText("Eliminar Posición");
        jButton_eliminar_posicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_eliminar_posicionMouseClicked(evt);
            }
        });

        jButton_busca_posicion.setText("Buscar Posición");
        jButton_busca_posicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_busca_posicionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_eliminar_elemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_eliminar_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_elemento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_busca_posicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_tamanio)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_tamanio)
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_elemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_agregar)
                            .addComponent(jButton_eliminar_elemento)
                            .addComponent(jButton_buscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_eliminar_posicion)
                            .addComponent(jButton_busca_posicion))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_agregarMouseClicked
        // TODO add your handling code here:
        String elemento = this.jTextField_elemento.getText();
        lista.Agregar(elemento);
        
        model_lista.addElement(elemento);
        this.jTextField_elemento.setText("");
        this.jLabel_tamanio.setText("Tamaño: " + lista.getTamanio());
    }//GEN-LAST:event_jButton_agregarMouseClicked

    private void jButton_eliminar_elementoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_eliminar_elementoMouseClicked
        // TODO add your handling code here:
        String elemento = this.jTextField_elemento.getText();
        int posicion = lista.EliminarElemento(elemento);
        
        if (posicion == -1) {
            JOptionPane.showMessageDialog(this, "No se puedo eliminar");
        } else {
            model_lista.remove(posicion);
        }
        this.jTextField_elemento.setText("");
        this.jLabel_tamanio.setText("Tamaño: " + lista.getTamanio());
    }//GEN-LAST:event_jButton_eliminar_elementoMouseClicked

    private void jButton_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_buscarMouseClicked
        // TODO add your handling code here:
        String elemento = this.jTextField_elemento.getText();
        int posicion = lista.BuscarElemento(elemento);
        
        if (posicion == -1) {
            JOptionPane.showMessageDialog(this, "No se puedo encontrar");
            this.jList_lista.clearSelection();
        } else {
            this.jList_lista.setSelectedIndex(posicion);
        }
        this.jTextField_elemento.setText("");
    }//GEN-LAST:event_jButton_buscarMouseClicked

    private void jButton_insertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_insertarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_insertarMouseClicked

    private void jButton_eliminar_posicionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_eliminar_posicionMouseClicked
        // TODO add your handling code here:
        int posicion = Integer.parseInt(this.jSpinner_posicion.getValue().toString());
        posicion = lista.EliminarPosicion(posicion);
        
        if (posicion == -1) {
            JOptionPane.showMessageDialog(this, "No se puedo eliminar");
        } else {
            model_lista.remove(posicion);
        }
        this.jTextField_elemento.setText("");
        this.jLabel_tamanio.setText("Tamaño: " + lista.getTamanio());
    }//GEN-LAST:event_jButton_eliminar_posicionMouseClicked

    private void jButton_busca_posicionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_busca_posicionMouseClicked
        // TODO add your handling code here:
        int posicion = Integer.parseInt(this.jSpinner_posicion.getValue().toString());
        String elemento = lista.BuscarPosicion(posicion);
        
        if (elemento.equals("")) {
            JOptionPane.showMessageDialog(this, "No se puedo encontrar");
            this.jList_lista.clearSelection();
        } else {
            this.jList_lista.setSelectedValue(elemento, rootPaneCheckingEnabled);
        }
        this.jTextField_elemento.setText("");
    }//GEN-LAST:event_jButton_busca_posicionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Lista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_agregar;
    private javax.swing.JButton jButton_busca_posicion;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_eliminar_elemento;
    private javax.swing.JButton jButton_eliminar_posicion;
    private javax.swing.JButton jButton_insertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_tamanio;
    private javax.swing.JList<String> jList_lista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_posicion;
    private javax.swing.JTextField jTextField_elemento;
    // End of variables declaration//GEN-END:variables
}
